# 创建子网,路由虚拟机，并给vm绑定浮动ip
- hosts: all
  tasks:
  - name: init private network
    os_network:
      state: present
      name: ljw-net

  - name: init private subnet   # 创建子网
    os_subnet:
      state: present
      name: ljw_subnet
      network_name: ljw-net
      cidr: 10.0.0.0/24
      allocation_pool_start: 10.0.0.10   #分配ip范围
      allocation_pool_end: 10.0.0.20
  - name: init router   # 创建路由
    os_router:
      state: present
      name: ljw-router
      network: public  # 外部网络
      interfaces:  # 链接子网接口
        - ljw_subnet 
  - name: create a vm1
    os_server:
      name: vm 
      image: centos7_20170621
      key_name: ljw
      flavor: 4C.8G
      security_groups: default
      nics:
        - net-name: ljw-net
      floating_ip_pools: public          #自动分配浮动ip

